@host = https://localhost:7014

POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "",
    "lastName": "",
    "email": "yesirkepov03@gmail.com",
    "password": "Qwerty1!"
}